[tool.poetry]
name = "cw3"
version = "0.1.0"
description = ""
authors = ["isa <ir.saldaeva@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
